### ISSUE TITLE
Device drivers for onboard USB bridges

### ISSUE THREAD

**Issue by wjgeorge** [neilpf2014/Fubar-ESP8266-IOT#1]
ch340:
http://www.wch.cn/download/CH341SER_MAC_ZIP.html

pl2303
http://www.prolific.com.tw/US/ShowProduct.aspx?p_id=229&pcid=41

cp2102
https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers

**Comment by neilpf2014** [comment]
Added link to USB drivers and udev rules
